### ISSUE TITLE
Sidekiq - Ruby errors when running related tasks

### ISSUE THREAD

**Issue by ewlarson** [geobtaa/geoportal#530]
Invoking a sidekiq-related task throws a Ruby error:

```bash
uldeploy@geomg:/var/www/geoportal/current$ RAILS_ENV=production bundle exec rake geoportal:sidekiq_stats
DEPRECATION WARNING: Initializing a Blacklight::Configuration::ViewConfig implicitly (by calling mapview) is deprecated. Call it as mapview! or pass initialize arguments. (called from block in <class:CatalogController> at /var/www/geoportal/releases/20230621211257/app/controllers/catalog_controller.rb:50)
rake aborted!
NoMethodError: undefined method `first' for nil:NilClass
/opt/data/geoportal/shared/bundle/ruby/3.0.0/gems/sidekiq-6.3.1/lib/sidekiq/api.rb:68:in `fetch_stats_fast!'
/opt/data/geoportal/shared/bundle/ruby/3.0.0/gems/sidekiq-6.3.1/lib/sidekiq/api.rb:11:in `initialize'
/var/www/geoportal/releases/20230621211257/lib/tasks/geoportal/geoportal_sidekiq.rake:21:in `new'
/var/www/geoportal/releases/20230621211257/lib/tasks/geoportal/geoportal_sidekiq.rake:21:in `block (2 levels) in <main>'
/opt/data/geoportal/shared/bundle/ruby/3.0.0/gems/appsignal-3.4.4/lib/appsignal/integrations/rake.rb:7:in `execute'
/opt/data/geoportal/shared/bundle/ruby/3.0.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/opt/ruby/bin/bundle:23:in `load'
/opt/ruby/bin/bundle:23:in `<main>'
Tasks: TOP => geoportal:sidekiq_stats
(See full trace by running task with --trace)
```

**Comment by ewlarson** [comment]
Upgrading sidekiq gem will resolve this issue, per SO:
https://stackoverflow.com/questions/74314906/heartbeat-unsupported-command-argument-type-falseclass-redis
